image: mcr.microsoft.com/dotnet/sdk:2.1

stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build

test:
  before_script:
    - dotnet tool install dotnet-reportgenerator-globaltool --version 4.8.13 --tool-path tools
  stage: test
  script:
    - 'dotnet test --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml